### PR TITLE
Issue162 testcase single zone commercial

### PR DESCRIPTION
**Pull request by taoyyt**
This is the emulator of Single Zone Commercial building from SDU, Denmark

### CODE REVIEW

**Comment by dhblum** [comment]
Thanks a lot @TaoYang-CFEI for making this PR.  This model is almost there I think.  I have a number of comments that should be addressed though:

- [ ] The directory structure should follow for example ``testcases/testcase1`` and ``testcases/testcase2``.  That is, within ``testcases/singleZoneCommercial``, there should be a ``models`` directory, ``doc`` directory, and ``config.py`` file.  Within ``/models`` is where you should place the file required for your model, and there should be a ``Resources`` directory for the data .csv files.
- [ ] Please generate the data .csv files and place them in the ``Resources`` directory.
- [ ] Please finalize the documentation of the model, as some sections are blank.
- [ ] ``OU44Emulator.Models.Validation.RealOccupancy.read_Tzone.KPIs`` should be tagged as ``Air zone Temperature``.
- [ ] ``OU44Emulator.Models.Validation.RealOccupancy.read_Q_el`` and ``OU44Emulator.Models.Validation.RealOccupancy.read_Q_h`` specify power measurements, however, they are actually energy measurements since they are after the integrators.  These measurements should be before the integrators.  Please also specify the unit as W.
- [ ] All Read and Overwrite blocks should specify units.  Use standard units, such as K, W, and ppm.  
- [ ] The definition of the construction ``floor`` should use ``Buildings.HeatTransfer.Data.OpaqueConstructions.Generic`` and also specify that the parameter ``nLay=2``.  Similar for ``roof`` and ``intWall`` (except for this one ``nLay=1``).
- [ ] You can probably speed up simulation time a lot if in your ``occ.txt`` file you only specify the times that the value changes, perhaps even by a particular threshold, rather than specifying a value every 60s.

**Comment by TaoYang-CFEI** [comment]
Many thanks for your comments @dhblum, the updated version has been uploaded, please take a look, further comments are more than welcome.

**Comment by dhblum** [comment]
@TaoYang-CFEI Thanks a lot for the revisions!  This looks very good, and addressed all of my comments I listed before.  

I am going to do some additional testing with the BOPTEST framework, add associated unit tests, and maybe fix some small typos I see in the documentation.  In this case, are you ok with me pushing some changes to your fork branch?

In the meantime, can you please add more details to the documentation of inputs and outputs?  Please add the variable name (e.g. "read_Tzone" - the name of the signal exchange block instance), unit, min, and max.  Also make sure the description matches what is in the signal exchange block instance.

After this, it would be good too to have another review check with the most recent review checklist, v1.3 (most updates are related to the BOPTEST stuff, and not as much the modeling, which has been reviewed by the checklist uploaded with the model already).  Is Valentin still available for this?

**Comment by TaoYang-CFEI** [comment]
@dhblum thanks for the feedback, please feel free to push any changes to my fork branch. I will further update the model with the comments. Besides, I am planning to update the newest review checklist myself if that is OK, since Valentin may not be available for it. Also, I think will provide the updated review checklist for Valentin's model within the next two weeks.

**Comment by dhblum** [comment]
@TaoYang-CFEI Ok I will push some changes and also look for your updates to the documentation (see [here](https://github.com/ibpsa/project1-boptest/blob/master/testcases/bestest_air/doc/index.html#L226) for an example).  

I think it would be better if someone other than you completed the review checklist, as the review process should serve as a peer review.  I can do that, having gone through the model once already.  If you can focus on reviewing Valentin's model within the next two weeks, that would be great.

**Comment by TaoYang-CFEI** [comment]
@dhblum Thanks a lot, that works great!

**Comment by dhblum** [comment]
@TaoYang-CFEI I was able to simulate the model for 1 year using cvode in Dymola.  However, when I try to simulate the model with JModelica (pyfmi) cvode solver, I get errors in the solver.  Have you ever tested simulating the model with JModelica?

**Comment by TaoYang-CFEI** [comment]
@dhblum I have not tested the model with JModelica.  I actually have no clue how the error comes either.

**Comment by dhblum** [comment]
Ok thanks @TaoYang-CFEI.  I'll be taking a look at it.

**Comment by dhblum** [comment]
Just an update here.  If I remove the PID controllers for the radiator and AHU valve and replace with constant 0s, it simulates ok.  So it seems to be something around the controls that are causing the issue.

**Comment by TaoYang-CFEI** [comment]
@dhblum Just want to make sure I understand correctly the error, then I can start to debug it.  Did you export the model fmu, and run it with python PyFMI interface instead of running the model itself in Jmodelica?

**Comment by dhblum** [comment]
@TaoYang-CFEI Thanks for clarifying.  No, I tried to run the model with JModelica.  I first compile the FMU with JModelica, then simulate the FMU with JModelica.

**Comment by dhblum** [comment]
@filokot Yes I get those warnings as well.  Also, while I'm glad you reproduced the error, just wanted to point out that it is not exact.  The integration time your error reports is 2923.212443 while mine is 0.095120.  I'm compiling using Buildings Library v7.0.0 and latest JModelica trunk (which is what BOPTEST uses in unit tests).

**Comment by taoyyt** [comment]
I have modified the model, the FMU is compiled and simulated for one month in Jmodelica, it seems like now the model can simulate fine.    

```
res1=RealOcc.simulate(final_time=2678400)
Final Run Statistics: --- e+06

 Number of steps                                 : 46222
 Number of function evaluations                  : 68554
 Number of Jacobian evaluations                  : 1634
 Number of function eval. due to Jacobian eval.  : 176472
 Number of error test failures                   : 3025
 Number of nonlinear iterations                  : 68320
 Number of nonlinear convergence failures        : 165
 Number of state function evaluations            : 46275
 Number of state events                          : 4
 Number of time events                           : 44

Solver options:

 Solver                   : CVode
 Linear multistep method  : BDF
 Nonlinear solver         : Newton
 Linear solver type       : DENSE
 Maximal order            : 5
 Tolerances (absolute)    : [  1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-06
   1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-06
   1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-06
   1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-06
   1.00000000e-06   1.00000000e-06   1.00000000e-06   3.00000000e-04
   3.00000000e-04   3.00000000e-04   3.00000000e-04   3.00000000e-04
   3.00000000e-04   3.00000000e-04   3.00000000e-04   2.93150000e-04
   2.93150000e-04   2.93150000e-04   2.93150000e-04   3.00000000e-04
   3.00000000e-04   3.00000000e-04   3.00000000e-04   3.00000000e-04
   2.93150000e-04   2.93150000e-04   2.93150000e-04   2.93150000e-04
   3.00000000e-04   3.00000000e-04   3.00000000e-04   3.00000000e-04
   3.00000000e-04   2.93150000e-04   2.93150000e-04   2.93150000e-04
   2.93150000e-04   3.00000000e-04   3.00000000e-04   3.00000000e-04
   3.00000000e-04   3.00000000e-04   2.93150000e-04   2.93150000e-04
   2.93150000e-04   2.93150000e-04   3.00000000e-04   3.00000000e-04
   3.00000000e-04   3.00000000e-04   3.00000000e-04   2.93150000e-04
   3.00000000e-04   3.00000000e-04   3.00000000e-04   3.00000000e-04
   2.93150000e-04   3.00000000e-04   3.00000000e-04   3.00000000e-04
   3.00000000e-04   3.00000000e-04   2.93150000e-04   1.00000000e-01
   1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-06
   1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-06
   1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-01
   1.00000000e-01   1.00000000e-01   1.00000000e-01   1.00000000e-01
   1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-06
   1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-06
   1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-06
   1.00000000e-06   1.00000000e-06   1.00000000e-06   1.00000000e-06]
 Tolerances (relative)    : 0.0001

Simulation interval    : 0.0 - 2678400.0 seconds.
Elapsed simulation time: 58.2263344 seconds.
```

**Comment by taoyyt** [comment]
@dhblum, I tried to simulate the model in Jmodelica with PyFMI for the full year, it has a new error "Failed to update the events". if I remember correctly, you mentioned the same issue in the meeting,  could you share some experience of fixing it. Thanks.

```
res1=RealOcc.simulate(final_time=31536000)
---------------------------------------------------------------------------
FMUException                              Traceback (most recent call last)
<ipython-input-128-9aabae11f47f> in <module>()
----> 1 res1=RealOcc.simulate(final_time=31536000)

src\pyfmi\fmi.pyx in pyfmi.fmi.FMUModelME2.simulate (src\pyfmi\fmi.c:81078)()

src\pyfmi\fmi.pyx in pyfmi.fmi.ModelBase._exec_simulate_algorithm (src\pyfmi\fmi.c:6103)()

src\pyfmi\fmi.pyx in pyfmi.fmi.ModelBase._exec_simulate_algorithm (src\pyfmi\fmi.c:6020)()

C:\Users\taoy\AppData\Roaming\JModelica.org-2.14\install\Python_64\pyfmi\fmi_algorithm_drivers.pyc in solve(self)
    517
    518         try:
--> 519             self.simulator.simulate(self.final_time, self.ncp)
    520         except:
    521             self.result_handler.simulation_end() #Close the potentially open result files

assimulo\ode.pyx in assimulo.ode.ODE.simulate (assimulo\ode.c:6667)()

assimulo\ode.pyx in assimulo.ode.ODE.simulate (assimulo\ode.c:6066)()

assimulo\explicit_ode.pyx in assimulo.explicit_ode.Explicit_ODE._simulate (assimulo\explicit_ode.c:4985)()

assimulo\explicit_ode.pyx in assimulo.explicit_ode.Explicit_ODE._simulate (assimulo\explicit_ode.c:4522)()

C:\Users\taoy\AppData\Roaming\JModelica.org-2.14\install\Python_64\pyfmi\simulation\assimulo_interface.pyc in handle_event(self, solver, event_info)
    867         self._model.enter_event_mode()
    868
--> 869         self._model.event_update()
    870         eInfo = self._model.get_event_info()
    871

src\pyfmi\fmi.pyx in pyfmi.fmi.FMUModelME2.event_update (src\pyfmi\fmi.c:79459)()

FMUException: Failed to update the events at time: 5.814000E+06.

```

**Comment by dhblum** [comment]
Thanks @taoyyt.  With your latest model I simulated:

- With Buildings Library version 7.0.0 (commit 903a06999fb514ebc1d0f58ef41b3f6dda0279ed)
- Ubuntu 18.04
- Dymola 2021 with cvode tol 1e-6 for 1 yr: OK
- JModelica Trunk from June 2019 for 1 yr: OK

Can you check your JModelica and model set up and compare to mine?

**Comment by taoyyt** [comment]
Thanks @dhblum, we have tested with the same model setup as yours (we did not modify the model itself), it simulated OK for one year. please see the attached log. 

terminal_log

**Comment by taoyyt** [comment]
@dhblum I followed the FinalizingTestCase guidance,  I got the following error when running code "make test_single_zone_commercial".  Do you have any ideas what the cause would be?
 
```
======================================================================
ERROR: test_peak_heat_day (test_single_zone_commercial.Run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001EA6EF19128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /scenario (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA6EF19128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Code\project1-boptest\testing\test_single_zone_commercial.py", line 31, in test_peak_heat_day
    self.run_time_period('peak_heat_day')
  File "C:\Code\project1-boptest\testing\utilities.py", line 632, in run_time_period
    requests.put('{0}/scenario'.format(self.url), data={'time_period':time_period})
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 131, in put
    return request('put', url, data=data, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /scenario (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA6EF19128>: Failed to 
establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

======================================================================
ERROR: test_typical_heat_day (test_single_zone_commercial.Run)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001EA6EF2B1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /scenario (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA6EF2B1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Code\project1-boptest\testing\test_single_zone_commercial.py", line 37, in test_typical_heat_day
    self.run_time_period('typical_heat_day')
  File "C:\Code\project1-boptest\testing\utilities.py", line 632, in run_time_period
    requests.put('{0}/scenario'.format(self.url), data={'time_period':time_period})
pters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /scenario (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA6EF2B1D0>: Failed to 
establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

----------------------------------------------------------------------
Ran 16 tests in 32.174s

FAILED (errors=16)
cd .. && make stop TESTCASE=single_zone_commercial
make[1]: Entering directory '/cygdrive/c/Code/project1-boptest'
docker stop boptest_single_zone_commercial
Error response from daemon: No such container: boptest_single_zone_commercial
makefile:22: recipe for target 'stop' failed
make[1]: *** [stop] Error 1
make[1]: Leaving directory '/cygdrive/c/Code/project1-boptest'
makefile:181: recipe for target 'test_single_zone_commercial' failed
make: *** [test_single_zone_commercial] Error 2
```

**Comment by dhblum** [comment]
Thanks for reporting @taoyyt!  It looks like the unit tests can't connect to the deployed test case, which indicates there is a problem deploying the test case in the first place.  It could be a number of things.  The unit tests deploy the test case in the background.  Can you please use the typical command to deploy your test case (running from repository root the command ``$ make run TESTCASE=single_zone_commercial``) and report any errors you see there?

**Comment by taoyyt** [comment]
Thanks for the sugguestions @dhblum. Just an update here, after correcting the building library version and python version, the errors now are 3 of 16. 
```
Found 16 tests to run in test_single_zone_commercial.py.

Running...
EE......E.......
======================================================================
ERROR: test_advance_false_overwrite (test_single_zone_commercial.API)
Test advancing of simulation with overwriting as false.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Code\project1-boptest\testing\utilities.py", line 491, in test_advance_false_overwrite
    df = pd.DataFrame.from_dict(y, orient = 'index', columns=['value'])
  File "C:\Users\taoy\.conda\envs\py2\lib\site-packages\pandas\core\frame.py", line 1118, in from_dict
    if len(data) > 0:
TypeError: object of type 'NoneType' has no len()

======================================================================
ERROR: test_advance_no_data (test_single_zone_commercial.API)
Test advancing of simulation with no input data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Code\project1-boptest\testing\utilities.py", line 455, in test_advance_no_data
    df = pd.DataFrame.from_dict(y, orient = 'index', columns=['value'])
  File "C:\Users\taoy\.conda\envs\py2\lib\site-packages\pandas\core\frame.py", line 1118, in from_dict
    if len(data) > 0:
TypeError: object of type 'NoneType' has no len()

======================================================================
ERROR: test_initialize (test_single_zone_commercial.API)
Test initialization of test simulation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Code\project1-boptest\testing\utilities.py", line 409, in test_initialize
    df = pd.DataFrame.from_dict(y, orient = 'index', columns=['value'])
  File "C:\Users\taoy\.conda\envs\py2\lib\site-packages\pandas\core\frame.py", line 1118, in from_dict
    if len(data) > 0:
TypeError: object of type 'NoneType' has no len()

----------------------------------------------------------------------
Ran 16 tests in 2.034s

FAILED (errors=3)
cd .. && make stop TESTCASE=single_zone_commercial
make[1]: Entering directory '/cygdrive/c/Code/project1-boptest'
docker stop boptest_single_zone_commercial
boptest_single_zone_commercial
make[1]: Leaving directory '/cygdrive/c/Code/project1-boptest'
```

**Comment by dhblum** [comment]
Thanks @taoyyt.  It's a bit odd that all other tests would run ok but those three would fail.  Could you:

1. Verify the reference .csv files that are generated from the other tests look reasonable to you.
2.  Use the ``$ make run TESTCASE=single_zone_commercial`` to deploy the test case and verify the ``/initialize`` and ``/advance`` APIs do not cause errors in the test case docker and return expected values.  It seems that in the unit test errors you show, they are returning ``None``, which indicates a potential problem within the test case docker I think.

**Comment by dhblum** [comment]
Made some good progress here.  Some remaining to-dos on documentation and resources data:

- [ ] Update component block naming to better align with conventions and add consistency, especially BOPTEST read and overwrite blocks.  Also update documentation sections stating I/O points with these new names.
- [ ] Update documentation text to be more descriptive about: 
- zone temperature set point schedule times and values,
- what the PI controllers are actually controlling (e.g. instead of "via controlling radiator power", say "via controlling radiator mixing valve control signal" or similar),
- available scenario descriptions (e.g. as done similarly in other test cases),
- reference IEEE paper https://ieeexplore.ieee.org/document/9236623 also.
- [ ] Update documentation with a hydronic system schematic.
- [ ] When above is done, export documentation to ``/doc``.
- [ ] Update ``models/Resources/setpoints.csv`` to match data in model - (lower set point values do not match zone temperature heating set point schedule in model).
- [ ] Check if other ``models/Resources/*.csv`` need to be updated.

**Comment by dhblum** [comment]
This is ready to merge if tests pass.

**Pull request merged**
