### PR TITLE
service synch

### PR DESCRIPTION
**Pull request by dhblum**
This is to synch the latest master with boptest-service.  In particular, to update the KPI calculation to the method implemented in https://github.com/ibpsa/project1-boptest/pull/265.  This should improve computational performance of boptest-service, since it calculates KPIs after every simulation step.

### CODE REVIEW

**Comment by dhblum** [comment]
@nllong @kbenne FYI.  Let me know if this is ok to merge.  Looks like the one build failed because of an issue trying to pull @SenHuang19 's Julia docker container for the ci testing of controller examples.  Not sure if this will be a continued problem.

**Comment by nllong** [comment]
I say merge it.

**Comment by nllong** [comment]
I'm more confident merging this now that the Pull Request tests passed, whilst the Branch failed.

**Comment by dhblum** [comment]
Yes I don't think there are issues with the code, as PR #265 passed tests before it was merged.  The fails due to the julia container issue I only started seeing with this PR.

**Pull request merged**
