### PR TITLE
Issue55 data generator module

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
This is for https://github.com/ibpsa/project1-boptest/issues/55

### CODE REVIEW

**Comment by dhblum** [comment]
Thanks for this @JavierArroyoBastida .  A few comments:

The test ``test_load_data_and_kpisjson`` does not check that the content of the kpis.json, only that it exists.  

Also, in the ``Data_Manager`` class, ``get_data()`` first checks that data is loaded, and if it is not loaded, then loads the data.  I think instead, data should get loaded on initialization of the class, which is a more intuitive time to load the data for future retrieval by other modules that need it.  Otherwise, if for some reason it takes time to load the data, a user or future developer may wonder why the first call of ``get_data ()`` takes longer than subsequent calls.

Therefore, I suggest the following to do:
- [] Check content of kpis.json in ``test_load_data_and_kpisjson``.
- [] Move the loading of data to the constructor of the ``Data_Manager`` class.

**Comment by JavierArroyoBastida** [comment]
@dhblum with the last commit I'm checking the content of kpis.json in `test_load_data_and_kpisjson`.
For the loading of data I just realized it is done in the constructor of the testcase:
https://github.com/JavierArroyoBastida/project1-boptest/blob/a0855adb7cb1525808c7d0a571be925a4a48296d/testcase.py#L38
So the check in `get_data()` is simply not needed, I'd just remove it.

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida .  Please, just a few more housekeeping items:
- [ ] Merge the latest ibpsa master.
- [ ] Add a readme to ``/data`` describing the purpose of the modules within.
- [ ] Update the ``/testing/README.md`` to include the data generator tests. 

I am going to make some additional edits to clarify some documentation I've noticed in the code.

**Comment by JavierArroyoBastida** [comment]
@dhblum I have included the items you were proposing. I believe it is ready to merge once you add your edits in the documentation. Please let me know if you find something else.

**Pull request merged**
