### PR TITLE
modify the reset API to take inputs from users regarding the starting time

### PR DESCRIPTION
**Pull request by SenHuang19**
this is related to #117

### CODE REVIEW

**Comment by dhblum** [comment]
@SenHuang19 Your suggested method implements a warm-up period by simulating from 0 to reset_time, to eliminate the effect of initial conditions, correct?  Should the behavior instead be similar to setting a new simulation start time in pyfmi or dymola, where this function just resets self.start_time, instead of first simulating the model from 0 to the reset time?  My arguments for this are that then the behavior is the same as expected in these other tools, the behavior is the same whether the simulation starts from 0, 1 day, or 300 days in terms of treatment of initial conditions (or lack there-of for now), and it does not require the time and data of simulation of 0 to 300 days if the user wants to start the simulation at 300 days.  What do you think?

**Comment by SenHuang19** [comment]
> @SenHuang19 Your suggested method implements a warm-up period by simulating from 0 to reset_time, to eliminate the effect of initial conditions, correct? Should the behavior instead be similar to setting a new simulation start time in pyfmi or dymola, where this function just resets self.start_time, instead of first simulating the model from 0 to the reset time? My arguments for this are that then the behavior is the same as expected in these other tools, the behavior is the same whether the simulation starts from 0, 1 day, or 300 days in terms of treatment of initial conditions (or lack there-of for now), and it does not require the time and data of simulation of 0 to 300 days if the user wants to start the simulation at 300 days. What do you think?

1. The reason to start the simulation from 0 is to make sure the simulation result is kind of consistent with similar initial states, regardless of when to start the simulation;
2. I acknowledge that it may take significant time to do this kind of reset 
3. Alternatively, may I suggest to create dynamic warming up periods. Specificially, if the user wants to reset the simulation to be starting from June 30, the warning period will be starting from June 28.

**Comment by dhblum** [comment]
This is an interesting point.  

My concern is us making assumptions about the necessary length of warming periods for all models and test scenarios.  My view is that this should be left to the user and/or to the specifiers of test scenarios, to be based on their specific application(s).  Then, the value assigned to the reset function can be specified based on their warming requirements.  All we do here is provide the functionality to specify it.

Or, are you already suggesting to allow a user to specify both a start time and a warming period length?

**Comment by dhblum** [comment]
Just to document, I think the design we landed on was that the API call would take start time and warm up period as arguments.

**Comment by dhblum** [comment]
@SenHuang19 I've created a new development branch for this at https://github.com/ibpsa/project1-boptest/tree/issue117_resetTime.  Please make a PR to this branch.

**Comment by dhblum** [comment]
Closing in favor of https://github.com/ibpsa/project1-boptest/pull/173.

**Pull request closed without merging**
