### PR TITLE
Issue325 bestest hydronic fmus

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
For https://github.com/ibpsa/project1-boptest/issues/325. @dhblum please let me know what you'd like to merge first if this one or https://github.com/ibpsa/project1-boptest/pull/324, to avoid updating references twice. I think it makes sense to do https://github.com/ibpsa/project1-boptest/pull/324 first since references are updated there already, in that case I'd get this one ready inmediately after.

### CODE REVIEW

**Comment by dhblum** [comment]
What you suggested makes sense.  I just merged #324. Also, I suppose this is another instance of needing to address https://github.com/ibpsa/project1-boptest/issues/183.

**Comment by JavierArroyoBastida** [comment]
Thanks for meging https://github.com/ibpsa/project1-boptest/pull/324. I'm going to update references here now. Also good point that you're raising about https://github.com/ibpsa/project1-boptest/issues/183, it has never been a priority but could certainly help in some cases like this one.

**Comment by JavierArroyoBastida** [comment]
@dhblum it has taken me a while to understand why forecast-related references have not needed update here, but in fact it has happened what was explained in https://github.com/ibpsa/project1-boptest/issues/183: references have been right all along even though the `wrapped.fmu` was using the wrong data. Tests would still pass because the right `wrapped.fmu` is compiled and used in the tests. Notice that in https://github.com/ibpsa/project1-boptest/pull/326/commits/7e0e19267270b4682df684368f0abfb6eca9b337 only `time_rat` needed update. So if that all makes sense and test pass this should be ready to merge too.

**Comment by dhblum** [comment]
Yeup, that makes sense, and is why I brought up #183.  Thanks for patching, I'll merge.

**Review by dhblum — APPROVED** [review]

**Pull request merged**
