### PR TITLE
Fix issue using parser with python3

### LINKED ISSUE #404: Parser is not compatible with python 3
There are very minor issues preventing the test case parser from working with both python 2 and 3.

### PR DESCRIPTION
**Pull request by kbenne**
close #404

### CODE REVIEW

**Comment by dhblum** [comment]
Thanks @kbenne for the PR.  Is a change not also needed at https://github.com/ibpsa/project1-boptest/blob/master/parsing/parser.py#L149 and https://github.com/ibpsa/project1-boptest/blob/master/parsing/parser.py#L163?

**Comment by dhblum** [comment]
@kbenne Also, please update the ``releasenotes.md`` in the backwards compatible section with a brief description and issue reference.

**Comment by kbenne** [comment]
> Thanks @kbenne for the PR. Is a change not also needed at https://github.com/ibpsa/project1-boptest/blob/master/parsing/parser.py#L149 and https://github.com/ibpsa/project1-boptest/blob/master/parsing/parser.py#L163?

I believe, based on my scenario, the answer is no. In python 3, the result of `keys()` can still be iterated, it appears you just can't concatenate them with the `+` operator because they are now ordered lists.

**Comment by kbenne** [comment]
Ah. Thank you. Didn't know the convention of the release notes.

**Comment by dhblum** [comment]
Ok I see, great.  Then this looks good.  I just moved the release notes description to the top (since the top has been most recent changes).  Will merge once tests pass.

**Review by dhblum — APPROVED** [review]

**Pull request merged**
