### PR TITLE
Issue107 iaq kpi

### PR DESCRIPTION
**Pull request by dhblum**
For https://github.com/ibpsa/project1-boptest/issues/107.

- CO2 tracking and measurements added to testcase1 and testcase2.
- Upper limit for CO2 added to test case data and design requirements documentation (header called ``UpperCO2``).  Value based on ASHRAE Guideline 36 Table 3.1.1.3.
- IAQ KPI calculation based on CO2 measurements added to KPI calculator (result called ``idis_tot``).
- Edits testcase1 and testcase2 to have non-zero iaq kpi calculations.
- Unittest results updated.

### CODE REVIEW

**Comment by dhblum** [comment]
@JavierArroyoBastida Can you review this when you get chance?

**Comment by JavierArroyoBastida** [comment]
@dhblum this is a very nice progress, thanks for working on this! My only two concerns:
1. I see KPIs for IAQ of actual test cases (testcase1 and testcase2) are both 0 which may not trigger any warning if something in the code affects IAQ calculation. 
2. Do we want to allow different CO2 thresholds for different zones? if yes that's to be worked out in https://github.com/ibpsa/project1-boptest/pull/133. In any case I suggest to merge this pull request already to the master and I'll update https://github.com/ibpsa/project1-boptest/pull/133 with these latest changes. We could even make use of the new multi-zone testcase  that needs to be developed on the issue121 branch as a test case with some ppm*h to address point 1.

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida for the review.  Yes, I think that it would be good to allow different thresholds for different zones, since different zone types may have different limits, or test case developers may develop to different thresholds.  This is similar to temperature setpoints.  Yes, it can be addressed in #133.

To your first point, before merging, I propose adding an arbitrary CO2 concentration to testcase1 that violates the limits for some amount of time in order to test the calculation of KPI.  I propose a sinusoidal CO2 concentration varying between 500 and 1000 diurnally.  Since the limit is 894, it will violate for some times.  I will make a new push soon for this.

**Comment by dhblum** [comment]
I also propose making testcase2 CO2 levels elevated to also test calculation of kpi above limit.

**Comment by dhblum** [comment]
@JavierArroyoBastida I've addressed your comments, can you review again?

**Comment by JavierArroyoBastida** [comment]
@dhblum this looks good to me. Please feel free to merge.

**Pull request merged**
