### PR TITLE
Issue660 update over write block multi res hydro

### PR DESCRIPTION
**Pull request by EttoreZ**
This PR is to address #653 by simplifying pump control and #660 by allowing setpoint change to control the boiler on and off signal.

### CODE REVIEW

**Review by dhblum — CHANGES_REQUESTED** [review]
This looks mostly good.  Need to:

- [ ] Check why model takes so much longer to run and whether still reasonable.  For example, unit test ``make test_multizone_residential_hydronic ARG="-s test_typical_heat_day,test_summer"`` takes [45 minutes](https://app.travis-ci.com/github/ibpsa/project1-boptest/jobs/624853443) in this PR while the last master build took [20 minutes](https://app.travis-ci.com/github/ibpsa/project1-boptest/jobs/624750282).  Similar timing discrepancy for ``make test_multizone_residential_hydronic ARG="-s test_peak_heat_day,test_shoulder"`` and ``make test_multizone_residential_hydronic ARG="-s API"``, the latter of which I think exceeds travis wait time of 90 min.
- [ ] Report in release notes what the KPI impacts are for full scenario tests of ``peak_heat_day`` and ``typical_heat_day`` (results from unit tests I've already written are only the first two days).
- [ ] Merge fix from https://github.com/ibpsa/project1-boptest/issues/673 once that issue resolved and update computational time ratio reference results.

**Comment by dhblum** [comment]
@EttoreZ I edited my review after a bit more investigation.

**Comment by EttoreZ** [comment]
> This looks mostly good from a software perspective. But need to:
> 
> * [x]  Check why model takes so much longer to run and whether still reasonable.  For example, unit test `make test_multizone_residential_hydronic ARG="-s test_typical_heat_day,test_summer"` takes [45 minutes](https://app.travis-ci.com/github/ibpsa/project1-boptest/jobs/624853443) in this PR while the last master build took [20 minutes](https://app.travis-ci.com/github/ibpsa/project1-boptest/jobs/624750282).  Similar timing discrepancy for `make test_multizone_residential_hydronic ARG="-s test_peak_heat_day,test_shoulder"` and `make test_multizone_residential_hydronic ARG="-s API"`, the latter of which I think exceeds travis wait time of 90 min.  I observed this when running unit tests locally too.
> * [x]  Once above is investigated, merge fix from [Fix computational time ratio reset #673](https://github.com/ibpsa/project1-boptest/issues/673) (now latest master) and update all reference results.
> * [x]  Report in release notes what the KPI impacts are for full scenario tests of `peak_heat_day` and `typical_heat_day` (results from unit tests I've already committed are only the first two days).

1) I found the issue with the slow down. To avoid having the boiler turn on before the pump does or off after the pump does, causing the simulation to crash, I added a delay of few seconds to the `on` signal for the boiler , and an hold of few seconds on the `off` signal of the pump. These two blocks caused a lot of time events that drastically increased computational time. In the last implementation I removed them, and instead multiplied the control signal of the boiler by a boolean that is 1 if `m_flow > 0.05*m_flow_nom`. Of course if someone starts to control the boiler directly with the overwrite, they might incur in a crash if they turn it on with no flow. After this change the computational time is comparable and 15% lower on an yearly simulation with Jmodelica on the workstation.

2) I merged the latest version of master and rerun the unit tests.

3) I updated the release notes with the percentage difference based on the full `peak_heat_day` and `typical_heat_day` scenarios.

**Comment by dhblum** [comment]
Thanks @EttoreZ.  Can the user turn on the pump without turning on the boiler?  Or will turning on the pump also auto turn on the boiler?

**Comment by EttoreZ** [comment]
If the user turns on the pump it will just enable to boiler, but the boiler will only turn on if the signal from the thermostat/PI control is > 0.  This is because the signals are multiplied with each other.

I see regarding the unit tests, I will be careful.

**Comment by EttoreZ** [comment]
@dhblum This PR is ready for final review and to be merged.

**Review by dhblum — APPROVED** [review]

**Pull request merged**
