### PR TITLE
Issue121 specify zone for data

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
For https://github.com/ibpsa/project1-boptest/issues/121
@dhblum could you please review? Before sending a pull request to the master I would:
1. Merge https://github.com/ibpsa/modelica-ibpsa/tree/issue1257_zoneDesignation to master.
2. Revert commit https://github.com/JavierArroyoBastida/project1-boptest/commit/c1b9dd52764e9da15a747ef29e8e05daf6a4c885 that is checking out issue1257_zoneDesignation of IBPSA.
3. Develop a unit tests for checking functionality when multi-zone specifications are used.

### CODE REVIEW

**Comment by dhblum** [comment]
@JavierArroyoBastida An update: 
- Modelica IBPSA library update being addressed in https://github.com/ibpsa/modelica-ibpsa/pull/1295.  
- parser edited and tested in https://github.com/ibpsa/project1-boptest/commit/000bade2ede8c3f76ab59161b73421099cba5fc0 and https://github.com/ibpsa/project1-boptest/commit/c6a4edeb504b5da1fa6f9388c962609cf1fecd40.

Can you update this PR by merging the latest BOPTEST master and fixing any conflicts?  Then, once Modelica IBPSA library update being addressed in https://github.com/ibpsa/modelica-ibpsa/pull/1295 is merged, we can remove https://github.com/ibpsa/project1-boptest/pull/133/commits/c1b9dd52764e9da15a747ef29e8e05daf6a4c885, merge this, create a multi-zone testcase on the issue121 branch, and then finally merge that to master.

**Comment by JavierArroyoBastida** [comment]
@dhblum, this sounds good to me. I'll work on it and contact you back once done.

**Comment by JavierArroyoBastida** [comment]
@dhblum now we have to come up with a multi-zone test case for unit testing. Have you given some thoughts to that? would you prefer a new dummy testcase3 equivalent to testcase1 and testcase2 but multi-zone? or would you rather prefer to use already one of the agreed BOPTEST testcases like the residential multi-zone hydronic or the commercial multi-zone hybrid simple? tomorrow I'm meeting with @icupeiro to start making his emulator BOPTEST ready.

**Comment by dhblum** [comment]
@JavierArroyoBastida I would prefer a new dummy testcase3 over relying on one of the IBPSA test cases.  It separates the testing / maintenance of the software itself from the development / maintenance of the IBPSA test cases.  Those test cases may also be quite complex, and a simpler test case will be easier to debug with issues in the future I think.

**Comment by JavierArroyoBastida** [comment]
@dhblum could you please review? 
Summarizing, this pull-request includes:
-	Developments to designate zone. 
-	Implementation of new testcase3 with two zones.
-	Multi-zone unit-testing with new testcase3.
-	Latest merges from master.

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida for this.  In general it looks like it accomplishes what we need.  I will merge this PR and re-open a PR for merge to master for closer review and any further updates.

Also noting that this is an initial implementation that addresses #157.

**Pull request merged**
