### PR TITLE
Issue113 Compute discomfort also for operative zone temperature readings

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
This is for https://github.com/ibpsa/project1-boptest/issues/113.

### CODE REVIEW

**Comment by dhblum** [comment]
We should create a test for this and also make sure any documentation is updated.

**Comment by JavierArroyoBastida** [comment]
@dhblum do you think we should implement a new testcase for unit-testing of this or use one of the existing?

**Comment by dhblum** [comment]
To limit maintenance of an additional test case, would it make sense to change one of the zones in testcase3 to measure operative temperature?

**Comment by JavierArroyoBastida** [comment]
That does make sense. It's actually what I had in mind. I'll take care of the implementation.

**Comment by JavierArroyoBastida** [comment]
@dhblum I think this is ready to merge once tests pass. Could you please check?

**Pull request merged**
