### PR TITLE
Issue348 bs21 workshop

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
This is for https://github.com/ibpsa/project1-boptest/issues/348. It includes presentations, rendered tutorial in pdf format, and the actual [notebook ](https://github.com/JavierArroyoBastida/project1-boptest/blob/issue348_bs21Workshop/docs/BS21Workshop_20210831/BOPTEST_Tutorial_BS2021Workshop.ipynb)with a badge to open it in Colab.

### CODE REVIEW

**Review by dhblum — CHANGES_REQUESTED** [review]
@JavierArroyoBastida I just suggest adding this content to /docs/workshops/BSWorkshop_20210831 (adding a workshops directory)

**Comment by JavierArroyoBastida** [comment]
Done! https://github.com/ibpsa/project1-boptest/pull/355/commits/8c42cbf41747e14d295261196af453c42a50642f.

**Review by dhblum — APPROVED** [review]
Great thanks!  Just added a quick note on the root readme.

**Comment by dhblum** [comment]
And updated release notes in 408e388

**Pull request merged**
