### PR TITLE
Add capability for browser access

### PR DESCRIPTION
**Pull request by SenHuang19**
This is for https://github.com/ibpsa/project1-boptest/issues/112.

### CODE REVIEW

**Comment by dhblum** [comment]
@SenHuang19 Can you add a unit test with example java code to test the capability?

**Comment by dhblum** [comment]
Please also merge the latest master, as I've updated for https://github.com/ibpsa/project1-boptest/issues/119.

**Comment by SenHuang19** [comment]
I added two html files for accessing the two emulator examples. Those html files contains controllers implemented in javascript. There are two ways to run the controllers: one is to run the html files with browser and the other is to run those in a headless mode with a python wrapper. The first way allows users to see the results with figures in runtime and the second way can be integrated in a automatic test. @dhblum please review it and I will add an unit test for the second way based on your comments if any.

**Comment by dhblum** [comment]
Hey @SenHuang19 Thanks for this.  Can you do the following?

1. Add a readme in ``examples/javascript`` for how to build and run the controller?  I built the controller for twoday_p and then tried to run it against a running testcase1 container, but nothing happened.  It just hung with:

```
project1-boptest/examples/javascript$ make run Script=twoday_p
docker run --name javascript_controller_twoday_p --detach=true --rm -it --network host javascript_controller_twoday_p /bin/bash && \
docker cp . javascript_controller_twoday_p:/home && \
docker exec -it javascript_controller_twoday_p /bin/bash -c "python /home/wrapper.py /home/twoday_p.html" && \
make copy_from_container ARGS=. && \
docker stop javascript_controller_twoday_p
ab4222d66154ff33280ac56367baec6694bbec7a900a01ab4aa3694f9446f8ad
```

2. Add code in the controller examples to output results csv and kpis csv similar to what is done in ``examples/julia``?  This will allow us to run these examples as part of unittests and check results.

**Comment by SenHuang19** [comment]
@dhblum  Does the "running testcase1 container" enable the cors?
I wiill add the readme and output section to the code

**Comment by dhblum** [comment]
@SenHuang19 It enables my cpu cores for about 10 seconds, and the only http request I see received on the server side is a GET for /name, and then nothing further for at least 4 or 5 minutes.

**Comment by dhblum** [comment]
For documentation purposes after our meeting, my issues described above related to not re-building the BOPTEST testcase with the changes to the ``restapi.py``.  If this is done, the javascript example works.

**Comment by dhblum** [comment]
Thanks for the updates @SenHuang19.  In general, they look good.  Can you please merge the latest ibpsa master to your repo branch where this is coming from?  Your branch is 100 commits behind.  Or, can you remake this pull request against a development branch I've created for this issue (issue112_brwoserAccess)?

**Comment by SenHuang19** [comment]
make a new pull request to issue112_brwoserAccess

**Pull request closed without merging**
