### PR TITLE
Issue289 bestest hp revision

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
For https://github.com/ibpsa/project1-boptest/issues/289.

### CODE REVIEW

**Comment by dhblum** [comment]
@JavierArroyoBastida This looks good to me if it is for you!

**Review by dhblum — APPROVED** [review]

**Comment by JavierArroyoBastida** [comment]
It's looking good to me too. I think it can be merged.

**Comment by JavierArroyoBastida** [comment]
Actually not just yet since the test case doc folder also needs to be updated.

**Comment by JavierArroyoBastida** [comment]
Now it can be merged.

**Comment by dhblum** [comment]
Ok thanks.  Was an odd error message as to why travis failed.  Re-started the check, hopefully it shows a pass this time, just to be sure.

**Comment by JavierArroyoBastida** [comment]
Sorry @dhblum, just found out another small detail that needed update.

**Comment by dhblum** [comment]
@JavierArroyoBastida Great.  Tests now pass.  I will merge.

**Pull request merged**
