### PR TITLE
Add bestest HP example.

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
This is for https://github.com/ibpsa/project1-boptest/issues/345. 
@kbenne please let me know if this works for you to test service with the `bestest_hyronic_heat_pump` case. 
The KPIs I get are:
```
KPI RESULTS 
-----------
tdis_tot: 19.214004362870106 Kh/zone
cost_tot: 0.7025804273828494 EUR/m^2
ener_tot: 2.762030365199603 kWh
emis_tot: 0.4612590709883337 kg CO2
idis_tot: 0.0 ppmh
time_rat: 5.6064019088076535e-05 
```
I should note that I've gotten the following error some times when testing myself: 
```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ec2-23-20-252-119.compute-1.amazonaws.com', port=80): Max retries exceeded with url: /advance/e3b9a1b9-052b-4496-a2c3-46d04d75a0a2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002811A6252B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
```
When I started testing I usually got that error randomly somewhere in the middle of the test, even when working with a wired connection. 
Then I used `time.sleep(1)` every control step to reduce the communication intensity and tests started working fine.  
After a while I tried again without sleeping time and the tests continued working properly. This makes me think that the failures at the beginning of my testing could be related to the server being saturated with dangling instances. 

Also @dhblum FYI.

### CODE REVIEW

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida.  Semi-unrelated, but would be good to correct the kpi units (few are missing /m^2 or /zone).  I think this actually needs to be corrected for all examples actually.  I'll make a separate issue.

**Comment by JavierArroyoBastida** [comment]
That's right. I've corrected KPI units in https://github.com/ibpsa/project1-boptest/pull/346/commits/304b584eb9ee03198aff2bd904683e9ca2c0f67f.

**Comment by dhblum** [comment]
Can this be closed with addition of https://github.com/ibpsa/project1-boptest/tree/master/docs/workshops/BS21Workshop_20210831?

**Comment by JavierArroyoBastida** [comment]
Yes, this can be closed.

**Pull request closed without merging**
