### PR TITLE
Issue159 testcase bestest hydronic

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
This is for https://github.com/ibpsa/project1-boptest/issues/159 and continuing with https://github.com/ibpsa/project1-boptest/pull/184.

### CODE REVIEW

**Comment by JavierArroyoBastida** [comment]
@dhblum, @Mathadon. These are the todo's to finalize this testcase: 

- [ ] 1. Update IDEAS with latest signal exchange blocks from IBPSA.
- [ ] 2. Update IDEAS model with changes from the update of the signal exchange blocks. 
- [ ] 3. Update testcase data keys also according to last BOPTEST updates. 
- [ ] 4. Add CO2 tags.
- [ ] 5. Add realistic highly dynamic price scenario from one year of historical day-ahead prices in Belgium. 
- [ ] 6. Swtch to operative zone temperature for discomfort calculation once https://github.com/ibpsa/project1-boptest/pull/198 is merged. 
- [ ] 7. Add `set_library_versions.sh` file. 
- [ ] 8. Add unit tests for the test case. 
- [ ] 9. Update documentation.

**Comment by dhblum** [comment]
@JavierArroyoBastida I think I will keep this open until the checklist is complete?  Let me know if you were thinking otherwise.

**Comment by JavierArroyoBastida** [comment]
@dhblum yes, this is not to be closed until checklist is complete. I'll reach you out then.

**Comment by dhblum** [comment]
:+1:

**Comment by dhblum** [comment]
Added ``set_library_versions.sh`` in https://github.com/ibpsa/project1-boptest/commit/9c00f8950af298921bf133f5d44d1cf74e386d08.

**Comment by JavierArroyoBastida** [comment]
@dhblum, @Mathadon what do you think of adding variable temperature set points (occupied/unoccupied) to the test case? as well as the possibility to externally overwrite such set points?

**Comment by dhblum** [comment]
I'm open to it.  I setback my apartment thermostat every time I leave.

**Comment by Mathadon** [comment]
Sounds realistic to me :)

**Comment by JavierArroyoBastida** [comment]
@dhblum, @Mathadon this is ready for final review and merging. 
Note that this line:
https://github.com/JavierArroyoBastida/project1-boptest/blob/108297c2344d4c6f271c891cb24970c7b04ab3b5/testcases/bestest_hydronic/models/set_library_versions.sh#L9 
needs to be changed to checkout master once IDEAS has merged https://github.com/open-ideas/IDEAS/pull/997

**Comment by Mathadon** [comment]
@JavierArroyoBastida I'm not that familiar with the boptest repo. Do you need input from me for this review?

**Comment by JavierArroyoBastida** [comment]
As far as you agree with what is in IDEAS (model and documentation) then it's fine. In here we basically extend that  model without modifying it, add the testcase data specified in the documentation of the model, and add unit tests around it. @dhblum already mentioned that he will take care of the review for this part.

**Comment by dhblum** [comment]
@JavierArroyoBastida Thanks for the updates.  You've removed unnecessary data columns from emissions, prices, etc., but did not remove them in the reference results.  Please do so.

**Comment by dhblum** [comment]
I've merged the latest master into the ``IBPSA:issue159_testcaseBestestHydronic``, so unittesting should be up to date, which is where I found the problem mentioned above.

**Comment by dhblum** [comment]
@JavierArroyoBastida I'm not sure what you mean by not adding latter commits.  The last commit on your branch is fa1035e
 and the last commit I see on this PR is also fa1035e?

**Comment by JavierArroyoBastida** [comment]
Looks like it had some delay... now it's ok.

**Pull request merged**
