### PR TITLE
Issue409 two zone hydronic apartment

### PR DESCRIPTION
**Pull request by EttoreZ**
This pull request if for issue #409 to add the two zone hydronic apartment.

### CODE REVIEW

**Comment by EttoreZ** [comment]
updated models after review

**Comment by EttoreZ** [comment]
The pull request was updated as per second round of review. Just a couple of comments:
- Documentation was updated
- Weather was updated (to avoid constant numbers in the last hours of the year)
- The control was not changed since as @Mathadon said. Those temperature warnings  are not a problem if the solver finds a solution by reducing the time step
- Latest version of the Master was merged

**Comment by dhblum** [comment]
Looks like tests fail because not all reference results were updated with some changes made. I can update if @EttoreZ unable before going on vacation.  

@JavierArroyoBastida and @EttoreZ Anything else on this needed still?

**Comment by EttoreZ** [comment]
@dhblum I updated the results and now they should pass the tests. I think I addressed all of @JavierArroyoBastida comments, but I will let him take a last look at the PR.

**Comment by dhblum** [comment]
Great, thanks. @EttoreZ!!

**Comment by JavierArroyoBastida** [comment]
Thanks for the updates, @EttoreZ! Before having a last look, I am a bit confused about how branches work now for this PR. My confusion stems from the commit that changes the weather file (https://github.com/EttoreZ/project1-boptest/commit/f3edac0d5b7e7bc46bb0196ba601a82c65da6726) being located at @EttoreZ's master, instead of at the origin branch of this PR (https://github.com/EttoreZ/project1-boptest/tree/issue409_TwoZoneHydronicApartment). Is that intentional? Note that changing the weather file was one of the requests of the review, so I would expect it belonging to this PR. Also, tests are not passing for some reason.

**Comment by EttoreZ** [comment]
@JavierArroyoBastida I don't why Github visualizes the branch in that way. Looking at my working tree :

**Comment by dhblum** [comment]
I also updated the ibpsa:issue409 branch with the latest master.

**Comment by JavierArroyoBastida** [comment]
I've gone through it again. Thanks @EttoreZ for addressing my comments! Nice to see tests are passing now. Only thing is that I see that you extended the description of `hydronicSystem_oveMpumCon_u` in the model, but this has not been reflected in the documentation. Could that be solved?

**Comment by EttoreZ** [comment]
@JavierArroyoBastida I updated the documentation (resuing the gethtmlIO script I saw there a couple more incosistencies). I also updated the branch to the latest master, so I guess for me it can be merged. Thank you for all the support!

**Review by JavierArroyoBastida — APPROVED** [review]
Looking good, thanks @EttoreZ! @dhblum I believe this emulator can be merged as well.

**Comment by dhblum** [comment]
Thanks @EttoreZ and @JavierArroyoBastida !  Merging to the staging branch.

**Pull request merged**
