### PR TITLE
Issue299 bestest hp setpoint

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
For https://github.com/ibpsa/project1-boptest/issues/299. 
@haraldwalnum @icupeiro FYI.

### CODE REVIEW

**Comment by dhblum** [comment]
I think just in reading the documentation, the differences between ``oveTSetHea_u``, ``oveTSetCoo_u``, and ``oveTSet_u`` is pretty confusing.  Is ``oveTSet_u`` not sufficient alone?  I think the offset in heating setpoint is part of the baseline controller, such that  ``oveTSetHea_u`` is unnecessary.  Then a user basically can override the setpoint given to the PI controller (which they could use to implement their own offset if they like based on the defined comfort region), or the heat pump actuation itself.  Also I think ``oveTSetCoo_u`` is unnecessary in general because there is no cooling system.  Thoughts?

**Comment by JavierArroyoBastida** [comment]
Right now one can either overwrite the the bounds of the comfort range or the zone temperature setpoint directly. If there is confusion I think it's better to keep only the zone temperature setpoint overwrite (`oveTSet_u`) and remove `oveTSetHea_u` and `oveTSetCoo_u`.

**Comment by dhblum** [comment]
I would vote to have only ``oveTSet_u``.

**Comment by icupeiro** [comment]
I also got confused when setting up the MPC, and as David pointed there is no cooling system.
So I would also vote to have only `oveTSet_u`

**Comment by JavierArroyoBastida** [comment]
Done! waiting for tests to pass.

**Pull request merged**
