### PR TITLE
Issue239 extend forecast

### PR DESCRIPTION
**Pull request by EttoreZ**
This pull request is to address issue #239, related to simulation across the year.

### CODE REVIEW

**Comment by dhblum** [comment]
Thanks @EttoreZ.  I just merged a pending PR that causes conflict now in the release notes.  Can you resolve the conflict?

**Comment by EttoreZ** [comment]
> Thanks @EttoreZ. I just merged a pending PR that causes conflict now in the release notes for this PR. Can you resolve the conflict?

Sure, thank you for the heads up @dhblum.

**Review by dhblum — COMMENTED** [review]
@EttoreZ Thank you for this.  The implementation splits the data at year-end to 1) before the end of the year inclusive of the last data point at the end of the year (midnight), and 2) after end of the year not inclusive of the first data point at the start of the year (midnight).  Please confirm this is what we agreed should be the case, rather than what is suggested in [this comment](https://github.com/ibpsa/project1-boptest/issues/239#issuecomment-1474436978).  This might be the case but I can't find it in my notes.  The implementation might make sense if this is what we agreed so that the forecast is more consistent for any interval through the full first year if a user only intends to simulate one year.  Can you please confirm and remind me?  Note I've plotted the results of unit tests below to show the performance of the implementation for forecast intervals of 1800 and 123 (as in the unit tests), compared to the reference boundary condition csv file (for an example relative humidity).

forecast_over_year_check

**Comment by Ye-Chuang** [comment]
您好，您的邮件我已收到，感谢您的来信，我会尽快给你回复。叶创

**Comment by EttoreZ** [comment]
> @EttoreZ Thank you for this. The implementation splits the data at year-end to 1) before the end of the year inclusive of the last data point at the end of the year (midnight), and 2) after end of the year not inclusive of the first data point at the start of the year (midnight). Please confirm this is what we agreed should be the case, rather than what is suggested in [this comment](https://github.com/ibpsa/project1-boptest/issues/239#issuecomment-1474436978). This might be the case but I can't find it in my notes. The implementation might make sense if this is what we agreed so that the forecast is more consistent for any interval through the full first year if a user only intends to simulate one year. Can you please confirm and remind me? Note I've plotted the results of unit tests below to show the performance of the implementation for forecast intervals of 1800 and 123 (as in the unit tests), compared to the reference boundary condition csv file (for an example relative humidity).
> 
> forecast_over_year_check

@dhblum thank you for the careful review. The implementation was indeed changed with the respect to the one mentioned in the comment for that exact reason, so that a 1 year simulation would be consistent.

**Comment by dhblum** [comment]
@EttoreZ Ok I see thank you!

**Review by dhblum — CHANGES_REQUESTED** [review]
@EttoreZ This is looking good, thanks.  Can you please add a description of the behavior, potentially with figure similar to what I posted in the discussion, to the design documentation here? https://github.com/ibpsa/project1-boptest/blob/master/docs/design/source/forecasts.rst.  In particular, you may add a subsection "Getting Forecasts Across Year-End"

**Review by dhblum — APPROVED** [review]
This is ready to merge once tests pass.

**Pull request merged**
