### PR TITLE
Update Introduction_to_the_BOPTEST_framework notebook

### LINKED ISSUE #507: Update/Add introductory tutorial
This issue is to update the introductory tutorial at https://github.com/ibpsa/project1-boptest/tree/master/docs/workshops/BS21Workshop_20210831 for v0.3.0 and also consider creating a testing environment to maintain that tutorial through version increments.

Related issue https://github.com/NREL/boptest-service/issues/16.

@jmythms has an updated version to PR and serve as a starting point for any additional edits to text and testing framework.

@JavierArroyoBastida, @kbenne.

### PR DESCRIPTION
**Pull request by jmythms**
Updated Introduction_to_the_BOPTEST_framework notebook to work with BOPTEST v0.3.0, attempting to fix #507 . 
Major changes:
1. Changed BOPTEST API base URL to http://api.boptest.net.
2. Changed the API calls to get info from 'payload'.
3. Added new KPIs.
4. Heat pump modulation signal is no longer in the measurements for bestest_hydronic_heat_pump so it was changed to the heat pump electrical power.
5. Added stop call at the end of the notebook.

### CODE REVIEW

**Comment by jmythms** [comment]
Converted to draft. Will pull in #508 after it is merged.

**Comment by dhblum** [comment]
#508 is merged.

**Comment by dhblum** [comment]
This should not pull in #508 as that would make it incompatible with BOPTEST v0.3.0.  I suggest keeping it compatible with v0.3.0 since that is what Service uses and this tutorial is based on use of Service.  This and the version in Service should ideally stay updated together.

**Comment by dhblum** [comment]
@jmythms Thanks for your updates.  A couple of additional edits from me:
- I reverted back to plotting the heat pump control signal (the way to get it changed from v0.1.0 to v0.3.0) for consistency with the older version of the tutorial and also to show how the control signal data can be retrieved.  
- I also made a bunch of text edits per updates we've made (especially linking to the website resources) since v0.1.0. 
- Merged latest master. 

The original tutorial was linked as a colab notebook, which is nice so users can simply run from a web browser.  This PR changes this to a simple ipython notebook.  I've uploaded the most recent versioin to my colab account.  @JavierArroyoBastida Any advice on how to link to this colab notebook?  The summary Todo is:
- [ ] Link notebook for use with colab

Also Todo is:
- [ ] Update the provided pdf once all is said and done.

**Comment by jmythms** [comment]
@dhblum Sorry for letting this PR go a bit stale. 

I think one way to make this a colab notebook would be to commit this file directly from your Google Colab account:
1. After opening the file in your colab account, go to File -> Save a copy in GitHub:
image
2. Put in the correct details for Repo, branch, file path, and commit message (optional): 
image

**Comment by dhblum** [comment]
Thanks @jmythms!  Looks like it worked to connect the colab.

**Comment by dhblum** [comment]
I believe this is ready to merge once tests pass.

**Pull request merged**
