### PR TITLE
Issue577 flask float

### PR DESCRIPTION
**Pull request by dhblum**
This is for #577.

### CODE REVIEW

**Comment by dhblum** [comment]
@kbenne See this PR regarding float handling related to BOPTEST-Service.

**Comment by kbenne** [comment]
> @kbenne See this PR regarding float handling related to BOPTEST-Service.

Cool. Do you think we need updates to other reference data files in the [pyfmi3 PR](https://github.com/ibpsa/project1-boptest/pull/536) when this change gets merged into that PR?

**Comment by dhblum** [comment]
@kbenne This PR updates references results for testcase 1 and 3 due to this change.  But it might be that those reference results will need to be updated again in that PR you reference (#536) with this change.  I can do a check by testing PR #536 with this change.

**Comment by dhblum** [comment]
This will be taken care of through #536.

**Comment by kbenne** [comment]
Are you going to merge this into https://github.com/ibpsa/project1-boptest/tree/issue146_pyfmi3_cs now?

**Comment by dhblum** [comment]
There would be merge conflicts with reference unit test results, and the fix itself is one line.  I was just going to implement the fix and update unit test results on the other PR, so will have that stuff pushed to that PR shortly.

**Comment by dhblum** [comment]
@kbenne See here, (https://github.com/ibpsa/project1-boptest/pull/536/commits/da4be6227eea189b1453d643777daa35500103a7) but I realized I need to merge latest master.

**Pull request closed without merging**
