### PR TITLE
Issue238 Update Quick-Start Docs

### PR DESCRIPTION
**Pull request by dhblum**
This is for #238.  In particular this PR:
- Updates ``README.md`` to change the section on running test cases to a "Quck-Start" section.
- Edit API section of ``README.md`` for more clarity
- Update the ``testcases/README.md`` to be more descriptive and make a table
- Rename the ``twoday_p`` and ``szvav_sup`` example test controller filenames to ``testcase1`` and ``testcase2`` to better associate with the test cases they are testing on.

### CODE REVIEW

**Review by JavierArroyoBastida — CHANGES_REQUESTED** [review]
[this line](https://github.com/ibpsa/project1-boptest/blob/b90fbab6c51357f163b3626122746a571a080120/testing/test_testcase1.py#L34) and [this line](https://github.com/ibpsa/project1-boptest/blob/b90fbab6c51357f163b3626122746a571a080120/testing/test_testcase2.py#L34) need to be adapted to `testcase1.run()` and `testcase2.run()`, respectively. Not sure if more changes in code are needed. For the rest of the changes they look fine to me.

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida.  Issues fixed in https://github.com/ibpsa/project1-boptest/pull/243/commits/54863c0829a1d5ae89060f24f6a228fb176526d5 and  https://github.com/ibpsa/project1-boptest/pull/243/commits/6a4fd9e0ed2c0b2e93d257c172576589135a9b71.

**Comment by JavierArroyoBastida** [comment]
Nice to see it's now passing the tests.

**Comment by dhblum** [comment]
@JavierArroyoBastida @SenHuang19 Please let me know if additional changes are needed.  Otherwise, use the github interface to approve the review.

**Review by JavierArroyoBastida — APPROVED** [review]

**Comment by SenHuang19** [comment]
The changes look good to me. For future, I suggest to extract the API interface parts from the example controllers and create a generic interface function to avoid code duplication

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida and @SenHuang19.  Sen, for your comment we could do that in a separate issue and PR.

**Pull request merged**
