### PR TITLE
Issue211 testcase bestest hydronic heat pump

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
This is for https://github.com/ibpsa/project1-boptest/issues/211 and uses the model from https://github.com/open-ideas/IDEAS/issues/1144. Commit https://github.com/JavierArroyoBastida/project1-boptest/commit/4c29c330f084b0eb685e9e870d41c4a354c59364 is to be reverted once https://github.com/open-ideas/IDEAS/issues/1144 is closed.

### CODE REVIEW

**Comment by JavierArroyoBastida** [comment]
@dhblum this is ready for review. Note that this line:
https://github.com/JavierArroyoBastida/project1-boptest/blob/e7932cab43ff43ec67b55c11544ce2d26cc4d027/testing/Dockerfile#L18
and this line:
https://github.com/JavierArroyoBastida/project1-boptest/blob/e7932cab43ff43ec67b55c11544ce2d26cc4d027/testcases/bestest_hydronic_heat_pump/models/set_library_versions.sh#L9
need to be changed to checkout IDEAS master once IDEAS has merged https://github.com/open-ideas/IDEAS/pull/1147.

**Comment by dhblum** [comment]
Ok I will plan this week to review.  Sorry for the delay.

**Comment by dhblum** [comment]
Completed review with peer review checklist v1.3 and returned to @JavierArroyoBastida via email.

**Comment by JavierArroyoBastida** [comment]
@dhblum I'm addressing your review comments in [this branch](https://github.com/open-ideas/IDEAS/tree/issue1166_reviewBestestHydronicHP). You can find my answers to your review [in this google document](https://docs.google.com/document/d/1oIfvZWTibkJ2_rDKMqhXYzRd1a2ojoCeGzGSDwpaDBk/edit?usp=sharing), feel free to use that doc and its version history to continue the discussion if needed.

**Comment by JavierArroyoBastida** [comment]
Note that this is not to be merged until https://github.com/open-ideas/IDEAS/tree/issue1166_reviewBestestHydronicHP is merged to IDEAS master and the corresponding changes applied to the BOPTEST repository to checkout the right IDEAS commit instead of that branch.

**Comment by dhblum** [comment]
@JavierArroyoBastida Your responses are reasonable to me.  Thanks for the changes and explanations.  I think this is ready to merge once coordinated issues are closed in IDEAS.

**Comment by JavierArroyoBastida** [comment]
@dhblum thanks a lot for your review! the corresponding branch in IDEAS has been merged to master and we're checking out now the ritght commit. I believe this is ready to merge.

**Pull request merged**
