### PR TITLE
Issue552 bs2023

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
@dhblum I believe this is ready to be merged.

### CODE REVIEW

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida.  Generally looks good since just adding material.  But can you add a note in the release notes that this content was added and also reference https://github.com/ibpsa/project1-boptest/issues/552, which is also to be closed by this PR?

**Comment by dhblum** [comment]
@JavierArroyoBastida And in addition to what I comment above, just merge the latest master to help with conflict management down the line?

**Comment by JavierArroyoBastida** [comment]
Sure! I just merged main and added a note to releasenotes.

**Comment by dhblum** [comment]
Thank you!

**Pull request merged**
