### PR TITLE
Issue224 Initialize return

### PR DESCRIPTION
**Pull request by JavierArroyoBastida**
For https://github.com/ibpsa/project1-boptest/issues/224.

### CODE REVIEW

**Comment by dhblum** [comment]
This looks good to me.  @SenHuang19 Any objections to merging?

**Comment by SenHuang19** [comment]
> This looks good to me. @SenHuang19 Any objections to merging?

I agree that this looks very good. Just one comment: do we need to add a class variable to the testcase which indicates the initialization is done successfully or not. In this case, we check if this variable in return from the "initialize_result" is true or false rather than if the return contains "time"

**Comment by dhblum** [comment]
@SenHuang19 I'm not sure I understand your comment.  ``initialize`` returns the measurement dictionary if successful, otherwise it returns None.  A controller can then check if None is returned to determine if successful.

**Comment by JavierArroyoBastida** [comment]
@SenHuang19 I see your point, I check that the `time` key is in the returned dictionary within the Julia examples [here](https://github.com/JavierArroyoBastida/project1-boptest/blob/13e71040c96afc723f4888dab118eaea438cb55b/examples/julia/twoday_p.jl#L45) and [here](https://github.com/JavierArroyoBastida/project1-boptest/blob/13e71040c96afc723f4888dab118eaea438cb55b/examples/julia/szvav_sup.jl#L45) because didn't find a way to directly check if return was a None. It may not be the most intuitive way to check that initialization was successful but is the best I could get with my Julia skills. Still I would avoid the overhead of a new variable definition in `testcase`, as @dhblum says, the controller can check if None is returned to determine if successful, there are probably several ways to do so.

**Comment by dhblum** [comment]
I changed the julia code to check for ``nothing`` in https://github.com/ibpsa/project1-boptest/pull/225/commits/3f680ecbb13982f7ef44a741d7f04025efd198b1.  @JavierArroyoBastida Hopefully you don't mind me pushing to your fork.

Is that an ok fix @SenHuang19?  I'd like to move this along if so.

**Comment by SenHuang19** [comment]
> I changed the julia code to check for `nothing` in [3f680ec](https://github.com/ibpsa/project1-boptest/commit/3f680ecbb13982f7ef44a741d7f04025efd198b1). @JavierArroyoBastida Hopefully you don't mind me pushing to your fork.
> 
> Is that an ok fix @SenHuang19? I'd like to move this along if so.

Yes, sounds good to me!

**Pull request merged**
