### PR TITLE
Issue244 set price scenario

### PR DESCRIPTION
**Pull request by dhblum**
This is for #244.  It:

- Adds API for GET and PUT ``/price_scenario``
- Adds and updates unit tests
- Adds ``'constant'`` price scenario as default in ``config.py`` for test cases

### CODE REVIEW

**Comment by dhblum** [comment]
@JavierArroyoBastida Before review, actually see this comments: https://github.com/ibpsa/project1-boptest/issues/244#issuecomment-721367335.

**Review by JavierArroyoBastida — APPROVED** [review]
I agree with the changes @dhblum, thanks for implementing this! A more complete implementation would indeed be including what is being described in [this comment](https://github.com/ibpsa/project1-boptest/issues/244#issuecomment-721367335). However, I'd go for a different pull request for that extension as this one is ready to merge.

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida for the review.  I was thinking I could update this PR based on [the comment](https://github.com/ibpsa/project1-boptest/issues/244#issuecomment-721367335).  It should only be a matter of updating the API endpoint, but the backend stuff should be able to stay mostly the same.

**Comment by dhblum** [comment]
@JavierArroyoBastida I've made updates based on that comment.

**Comment by JavierArroyoBastida** [comment]
looking good to me as well. Thanks @dhblum!

**Pull request merged**
