### PR TITLE
Issue150 update docs

### PR DESCRIPTION
**Pull request by dhblum**
This is for #150.  Related to KPI definitions and descriptions.  Edited some phrasing in all, but primary updates to:

- IAQ Discomfort
- Installation Metrics

### CODE REVIEW

**Comment by dhblum** [comment]
@yanchenpnnl Thank you very much for reviewing, please provide any other comments as well.

What about "Indoor Air Quality Violation"?  I like violation more than dissatisfaction.

**Comment by yanchenpnnl** [comment]
@dhblum Sure, I will try my best to go through the other changes within this week.
I like "Violation", that sets a strong term that we care about IAQ.  Let's use "Indoor Air Quality Violation".  Thank you!

**Comment by dhblum** [comment]
Sounds good to me.  Thanks!

Note that the changes are just to reflect the discussion results from Rome minutes: https://github.com/ibpsa/project1/tree/master/meetings/2019-08-31-expert-meeting-rome/wp_1_2.

**Comment by dhblum** [comment]
Hey @yanchenpnnl Just let me know if you have any further comments when you get a chance.

**Pull request merged**
