### PR TITLE
Sync master and boptest-service

### PR DESCRIPTION
**Pull request by nllong**
Hi @dhblum -- Can you merge master into boptest-service, it is a clean merge? Thanks!

### CODE REVIEW

**Comment by dhblum** [comment]
Hey @nllong I'm sorry but not quite clean, the following need to be addressed first:

- https://github.com/ibpsa/project1-boptest/issues/276 - can replicate existing service functionality by updating line 230 of ``worker/step_fmu.py``.
- https://github.com/ibpsa/project1-boptest/issues/278 - should be a simple patch.

@kbenne and I have started thinking about a testing infrastructure for service to help with this.

**Comment by nllong** [comment]
> Hey @nllong I'm sorry but not quite clean, the following need to be addressed first:
> 
> * #276 - can replicate existing service functionality by updating line 230 of `worker/step_fmu.py`.
> * #278 - should be a simple patch.
> 
> @kbenne and I have started thinking about a testing infrastructure for service to help with this.

Doh!  I saw no conflicts, so I assumed we were good. Let me know how I can help!

**Comment by kbenne** [comment]
> Hey @nllong I'm sorry but not quite clean, the following need to be addressed first:
> 
> * #276 - can replicate existing service functionality by updating line 230 of `worker/step_fmu.py`.
> * #278 - should be a simple patch.
> 
> @kbenne and I have started thinking about a testing infrastructure for service to help with this.

@dhblum  I'll plan to connect with you by the end of the week after I have reviewed a little. For reference there are end to end integration tests in Alfalfa here https://github.com/NREL/alfalfa/tree/develop/tests/integration and ideally we would align the approaches. Specific fmu tests for example are https://github.com/NREL/alfalfa/blob/develop/tests/integration/test_single_zone_vav_fmu.py and https://github.com/NREL/alfalfa/blob/develop/tests/integration/test_simple_thermostat_fmu.py

**Comment by dhblum** [comment]
Closing, rather use https://github.com/ibpsa/project1-boptest/pull/288 instead which implements the fixes for the issues I pointed out above.

An issue to setup boptest-service testing was created at https://github.com/ibpsa/project1-boptest/issues/282 and should be used for further discussion.

**Pull request closed without merging**
